### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by stwomack** [garethr/puppet-docker-swarm-example#2]
This is with the default 2 nodes, swarm-1 and swarm-2:

root@swarm-1:~# docker -H tcp://localhost:3000 info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 0
CPUs: 0
Total Memory: 0 B
Name: 812c9cb39e09

**Comment by stwomack** [comment]
root@swarm-1:~# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
812c9cb39e09        swarm               "/swarm manage consu   5 minutes ago       Up 5 minutes        0.0.0.0:3000->2375/tcp   goofy_darwin  
bdfe68751e97        swarm               "/swarm join --addr=   5 minutes ago       Up 5 minutes        2375/tcp                 compassionate_perlman

**Comment by rooprob** [comment]
The solution I found was to make some updates to the project - upgrade kernel (I have success on 4.2), tweak the modules and add some additional parameters. I'll push up the updates when I've finished....

**Comment by BarnumD** [comment]
Is this document even still valid in docker 17.05?  Does swarm still operate as containers?  I thought it was more built in now.

**Comment by Xtigyro** [comment]
> Is this document even still valid in docker 17.05? Does swarm still operate as containers? I thought it was more built in now.

I've fixed the code in a fork of mine and also used the much newer versions of the different components. - https://github.com/Xtigyro/puppet-docker-swarm-example

**Comment by Xtigyro** [comment]
Also - I've created a PR: https://github.com/garethr/puppet-docker-swarm-example/pull/3.
